/* 
 * NiFi Rest Api
 *
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.9.1
 * Contact: dev@nifi.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace NiFi.Swagger.Core.Api
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;

    using NiFi.Swagger.Core.Client;
    using NiFi.Swagger.Core.Model;

    using RestSharp;

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReportingTasksApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Clears the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ComponentStateEntity</returns>
        ComponentStateEntity ClearState (string id);

        /// <summary>
        /// Clears the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ComponentStateEntity</returns>
        ApiResponse<ComponentStateEntity> ClearStateWithHttpInfo (string id);
        /// <summary>
        /// Gets a reporting task property descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>PropertyDescriptorEntity</returns>
        PropertyDescriptorEntity GetPropertyDescriptor (string id, string propertyName);

        /// <summary>
        /// Gets a reporting task property descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>ApiResponse of PropertyDescriptorEntity</returns>
        ApiResponse<PropertyDescriptorEntity> GetPropertyDescriptorWithHttpInfo (string id, string propertyName);
        /// <summary>
        /// Gets a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ReportingTaskEntity</returns>
        ReportingTaskEntity GetReportingTask (string id);

        /// <summary>
        /// Gets a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        ApiResponse<ReportingTaskEntity> GetReportingTaskWithHttpInfo (string id);
        /// <summary>
        /// Gets the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ComponentStateEntity</returns>
        ComponentStateEntity GetState (string id);

        /// <summary>
        /// Gets the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ComponentStateEntity</returns>
        ApiResponse<ComponentStateEntity> GetStateWithHttpInfo (string id);
        /// <summary>
        /// Deletes a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>ReportingTaskEntity</returns>
        ReportingTaskEntity RemoveReportingTask (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null);

        /// <summary>
        /// Deletes a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        ApiResponse<ReportingTaskEntity> RemoveReportingTaskWithHttpInfo (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null);
        /// <summary>
        /// Updates a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>ReportingTaskEntity</returns>
        ReportingTaskEntity UpdateReportingTask (string id, ReportingTaskEntity body);

        /// <summary>
        /// Updates a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        ApiResponse<ReportingTaskEntity> UpdateReportingTaskWithHttpInfo (string id, ReportingTaskEntity body);
        /// <summary>
        /// Updates run status of a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>ReportingTaskEntity</returns>
        ReportingTaskEntity UpdateRunStatus (string id, ReportingTaskRunStatusEntity body);

        /// <summary>
        /// Updates run status of a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        ApiResponse<ReportingTaskEntity> UpdateRunStatusWithHttpInfo (string id, ReportingTaskRunStatusEntity body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Clears the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ComponentStateEntity</returns>
        System.Threading.Tasks.Task<ComponentStateEntity> ClearStateAsync (string id);

        /// <summary>
        /// Clears the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ComponentStateEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentStateEntity>> ClearStateAsyncWithHttpInfo (string id);
        /// <summary>
        /// Gets a reporting task property descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>Task of PropertyDescriptorEntity</returns>
        System.Threading.Tasks.Task<PropertyDescriptorEntity> GetPropertyDescriptorAsync (string id, string propertyName);

        /// <summary>
        /// Gets a reporting task property descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>Task of ApiResponse (PropertyDescriptorEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<PropertyDescriptorEntity>> GetPropertyDescriptorAsyncWithHttpInfo (string id, string propertyName);
        /// <summary>
        /// Gets a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        System.Threading.Tasks.Task<ReportingTaskEntity> GetReportingTaskAsync (string id);

        /// <summary>
        /// Gets a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> GetReportingTaskAsyncWithHttpInfo (string id);
        /// <summary>
        /// Gets the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ComponentStateEntity</returns>
        System.Threading.Tasks.Task<ComponentStateEntity> GetStateAsync (string id);

        /// <summary>
        /// Gets the state for a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ComponentStateEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentStateEntity>> GetStateAsyncWithHttpInfo (string id);
        /// <summary>
        /// Deletes a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        System.Threading.Tasks.Task<ReportingTaskEntity> RemoveReportingTaskAsync (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null);

        /// <summary>
        /// Deletes a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> RemoveReportingTaskAsyncWithHttpInfo (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null);
        /// <summary>
        /// Updates a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        System.Threading.Tasks.Task<ReportingTaskEntity> UpdateReportingTaskAsync (string id, ReportingTaskEntity body);

        /// <summary>
        /// Updates a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> UpdateReportingTaskAsyncWithHttpInfo (string id, ReportingTaskEntity body);
        /// <summary>
        /// Updates run status of a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        System.Threading.Tasks.Task<ReportingTaskEntity> UpdateRunStatusAsync (string id, ReportingTaskRunStatusEntity body);

        /// <summary>
        /// Updates run status of a reporting task
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> UpdateRunStatusAsyncWithHttpInfo (string id, ReportingTaskRunStatusEntity body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReportingTasksApi : IReportingTasksApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportingTasksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReportingTasksApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            this.ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportingTasksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReportingTasksApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            this.ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (this._exceptionFactory != null && this._exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return this._exceptionFactory;
            }
            set { this._exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Clears the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ComponentStateEntity</returns>
        public ComponentStateEntity ClearState (string id)
        {
             ApiResponse<ComponentStateEntity> localVarResponse = this.ClearStateWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Clears the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ComponentStateEntity</returns>
        public ApiResponse< ComponentStateEntity > ClearStateWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->ClearState");

            var localVarPath = "/reporting-tasks/{id}/state/clear-requests";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ClearState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentStateEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ComponentStateEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentStateEntity)));
        }

        /// <summary>
        /// Clears the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ComponentStateEntity</returns>
        public async System.Threading.Tasks.Task<ComponentStateEntity> ClearStateAsync (string id)
        {
             ApiResponse<ComponentStateEntity> localVarResponse = await this.ClearStateAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Clears the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ComponentStateEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentStateEntity>> ClearStateAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->ClearState");

            var localVarPath = "/reporting-tasks/{id}/state/clear-requests";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ClearState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentStateEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ComponentStateEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentStateEntity)));
        }

        /// <summary>
        /// Gets a reporting task property descriptor 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>PropertyDescriptorEntity</returns>
        public PropertyDescriptorEntity GetPropertyDescriptor (string id, string propertyName)
        {
             ApiResponse<PropertyDescriptorEntity> localVarResponse = this.GetPropertyDescriptorWithHttpInfo(id, propertyName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a reporting task property descriptor 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>ApiResponse of PropertyDescriptorEntity</returns>
        public ApiResponse< PropertyDescriptorEntity > GetPropertyDescriptorWithHttpInfo (string id, string propertyName)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetPropertyDescriptor");
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new ApiException(400, "Missing required parameter 'propertyName' when calling ReportingTasksApi->GetPropertyDescriptor");

            var localVarPath = "/reporting-tasks/{id}/descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (propertyName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "propertyName", propertyName)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetPropertyDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PropertyDescriptorEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PropertyDescriptorEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PropertyDescriptorEntity)));
        }

        /// <summary>
        /// Gets a reporting task property descriptor 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>Task of PropertyDescriptorEntity</returns>
        public async System.Threading.Tasks.Task<PropertyDescriptorEntity> GetPropertyDescriptorAsync (string id, string propertyName)
        {
             ApiResponse<PropertyDescriptorEntity> localVarResponse = await this.GetPropertyDescriptorAsyncWithHttpInfo(id, propertyName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a reporting task property descriptor 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="propertyName">The property name.</param>
        /// <returns>Task of ApiResponse (PropertyDescriptorEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PropertyDescriptorEntity>> GetPropertyDescriptorAsyncWithHttpInfo (string id, string propertyName)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetPropertyDescriptor");
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new ApiException(400, "Missing required parameter 'propertyName' when calling ReportingTasksApi->GetPropertyDescriptor");

            var localVarPath = "/reporting-tasks/{id}/descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (propertyName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "propertyName", propertyName)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetPropertyDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PropertyDescriptorEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PropertyDescriptorEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PropertyDescriptorEntity)));
        }

        /// <summary>
        /// Gets a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ReportingTaskEntity</returns>
        public ReportingTaskEntity GetReportingTask (string id)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = this.GetReportingTaskWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        public ApiResponse< ReportingTaskEntity > GetReportingTaskWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Gets a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        public async System.Threading.Tasks.Task<ReportingTaskEntity> GetReportingTaskAsync (string id)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = await this.GetReportingTaskAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> GetReportingTaskAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Gets the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ComponentStateEntity</returns>
        public ComponentStateEntity GetState (string id)
        {
             ApiResponse<ComponentStateEntity> localVarResponse = this.GetStateWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>ApiResponse of ComponentStateEntity</returns>
        public ApiResponse< ComponentStateEntity > GetStateWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetState");

            var localVarPath = "/reporting-tasks/{id}/state";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentStateEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ComponentStateEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentStateEntity)));
        }

        /// <summary>
        /// Gets the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ComponentStateEntity</returns>
        public async System.Threading.Tasks.Task<ComponentStateEntity> GetStateAsync (string id)
        {
             ApiResponse<ComponentStateEntity> localVarResponse = await this.GetStateAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the state for a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <returns>Task of ApiResponse (ComponentStateEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentStateEntity>> GetStateAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->GetState");

            var localVarPath = "/reporting-tasks/{id}/state";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentStateEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ComponentStateEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentStateEntity)));
        }

        /// <summary>
        /// Deletes a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>ReportingTaskEntity</returns>
        public ReportingTaskEntity RemoveReportingTask (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = this.RemoveReportingTaskWithHttpInfo(id, version, clientId, disconnectedNodeAcknowledged);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        public ApiResponse< ReportingTaskEntity > RemoveReportingTaskWithHttpInfo (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->RemoveReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (version != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "version", version)); // query parameter
            if (clientId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "clientId", clientId)); // query parameter
            if (disconnectedNodeAcknowledged != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "disconnectedNodeAcknowledged", disconnectedNodeAcknowledged)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("RemoveReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Deletes a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        public async System.Threading.Tasks.Task<ReportingTaskEntity> RemoveReportingTaskAsync (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = await this.RemoveReportingTaskAsyncWithHttpInfo(id, version, clientId, disconnectedNodeAcknowledged);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="version">The revision is used to verify the client is working with the latest version of the flow. (optional)</param>
        /// <param name="clientId">If the client id is not specified, new one will be generated. This value (whether specified or generated) is included in the response. (optional)</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed. (optional, default to false)</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> RemoveReportingTaskAsyncWithHttpInfo (string id, string version = null, string clientId = null, bool? disconnectedNodeAcknowledged = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->RemoveReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "*/*"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (version != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "version", version)); // query parameter
            if (clientId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "clientId", clientId)); // query parameter
            if (disconnectedNodeAcknowledged != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "disconnectedNodeAcknowledged", disconnectedNodeAcknowledged)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("RemoveReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Updates a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>ReportingTaskEntity</returns>
        public ReportingTaskEntity UpdateReportingTask (string id, ReportingTaskEntity body)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = this.UpdateReportingTaskWithHttpInfo(id, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        public ApiResponse< ReportingTaskEntity > UpdateReportingTaskWithHttpInfo (string id, ReportingTaskEntity body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->UpdateReportingTask");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ReportingTasksApi->UpdateReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("UpdateReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Updates a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        public async System.Threading.Tasks.Task<ReportingTaskEntity> UpdateReportingTaskAsync (string id, ReportingTaskEntity body)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = await this.UpdateReportingTaskAsyncWithHttpInfo(id, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task configuration details.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> UpdateReportingTaskAsyncWithHttpInfo (string id, ReportingTaskEntity body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->UpdateReportingTask");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ReportingTasksApi->UpdateReportingTask");

            var localVarPath = "/reporting-tasks/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("UpdateReportingTask", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Updates run status of a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>ReportingTaskEntity</returns>
        public ReportingTaskEntity UpdateRunStatus (string id, ReportingTaskRunStatusEntity body)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = this.UpdateRunStatusWithHttpInfo(id, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates run status of a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>ApiResponse of ReportingTaskEntity</returns>
        public ApiResponse< ReportingTaskEntity > UpdateRunStatusWithHttpInfo (string id, ReportingTaskRunStatusEntity body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->UpdateRunStatus");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ReportingTasksApi->UpdateRunStatus");

            var localVarPath = "/reporting-tasks/{id}/run-status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("UpdateRunStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

        /// <summary>
        /// Updates run status of a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>Task of ReportingTaskEntity</returns>
        public async System.Threading.Tasks.Task<ReportingTaskEntity> UpdateRunStatusAsync (string id, ReportingTaskRunStatusEntity body)
        {
             ApiResponse<ReportingTaskEntity> localVarResponse = await this.UpdateRunStatusAsyncWithHttpInfo(id, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates run status of a reporting task 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The reporting task id.</param>
        /// <param name="body">The reporting task run status.</param>
        /// <returns>Task of ApiResponse (ReportingTaskEntity)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReportingTaskEntity>> UpdateRunStatusAsyncWithHttpInfo (string id, ReportingTaskRunStatusEntity body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ReportingTasksApi->UpdateRunStatus");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ReportingTasksApi->UpdateRunStatus");

            var localVarPath = "/reporting-tasks/{id}/run-status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("UpdateRunStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReportingTaskEntity>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ReportingTaskEntity) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReportingTaskEntity)));
        }

    }
}
