/* 
 * NiFi Rest Api
 *
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.9.1
 * Contact: dev@nifi.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace NiFi.Swagger.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;

    using Newtonsoft.Json;

    /// <summary>
    /// FlowSnippetDTO
    /// </summary>
    [DataContract]
    public partial class FlowSnippetDTO :  IEquatable<FlowSnippetDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlowSnippetDTO" /> class.
        /// </summary>
        /// <param name="processGroups">The process groups in this flow snippet..</param>
        /// <param name="remoteProcessGroups">The remote process groups in this flow snippet..</param>
        /// <param name="processors">The processors in this flow snippet..</param>
        /// <param name="inputPorts">The input ports in this flow snippet..</param>
        /// <param name="outputPorts">The output ports in this flow snippet..</param>
        /// <param name="connections">The connections in this flow snippet..</param>
        /// <param name="labels">The labels in this flow snippet..</param>
        /// <param name="funnels">The funnels in this flow snippet..</param>
        /// <param name="controllerServices">The controller services in this flow snippet..</param>
        public FlowSnippetDTO(List<ProcessGroupDTO> processGroups = default(List<ProcessGroupDTO>), List<RemoteProcessGroupDTO> remoteProcessGroups = default(List<RemoteProcessGroupDTO>), List<ProcessorDTO> processors = default(List<ProcessorDTO>), List<PortDTO> inputPorts = default(List<PortDTO>), List<PortDTO> outputPorts = default(List<PortDTO>), List<ConnectionDTO> connections = default(List<ConnectionDTO>), List<LabelDTO> labels = default(List<LabelDTO>), List<FunnelDTO> funnels = default(List<FunnelDTO>), List<ControllerServiceDTO> controllerServices = default(List<ControllerServiceDTO>))
        {
            this.ProcessGroups = processGroups;
            this.RemoteProcessGroups = remoteProcessGroups;
            this.Processors = processors;
            this.InputPorts = inputPorts;
            this.OutputPorts = outputPorts;
            this.Connections = connections;
            this.Labels = labels;
            this.Funnels = funnels;
            this.ControllerServices = controllerServices;
        }
        
        /// <summary>
        /// The process groups in this flow snippet.
        /// </summary>
        /// <value>The process groups in this flow snippet.</value>
        [DataMember(Name="processGroups", EmitDefaultValue=false)]
        public List<ProcessGroupDTO> ProcessGroups { get; set; }

        /// <summary>
        /// The remote process groups in this flow snippet.
        /// </summary>
        /// <value>The remote process groups in this flow snippet.</value>
        [DataMember(Name="remoteProcessGroups", EmitDefaultValue=false)]
        public List<RemoteProcessGroupDTO> RemoteProcessGroups { get; set; }

        /// <summary>
        /// The processors in this flow snippet.
        /// </summary>
        /// <value>The processors in this flow snippet.</value>
        [DataMember(Name="processors", EmitDefaultValue=false)]
        public List<ProcessorDTO> Processors { get; set; }

        /// <summary>
        /// The input ports in this flow snippet.
        /// </summary>
        /// <value>The input ports in this flow snippet.</value>
        [DataMember(Name="inputPorts", EmitDefaultValue=false)]
        public List<PortDTO> InputPorts { get; set; }

        /// <summary>
        /// The output ports in this flow snippet.
        /// </summary>
        /// <value>The output ports in this flow snippet.</value>
        [DataMember(Name="outputPorts", EmitDefaultValue=false)]
        public List<PortDTO> OutputPorts { get; set; }

        /// <summary>
        /// The connections in this flow snippet.
        /// </summary>
        /// <value>The connections in this flow snippet.</value>
        [DataMember(Name="connections", EmitDefaultValue=false)]
        public List<ConnectionDTO> Connections { get; set; }

        /// <summary>
        /// The labels in this flow snippet.
        /// </summary>
        /// <value>The labels in this flow snippet.</value>
        [DataMember(Name="labels", EmitDefaultValue=false)]
        public List<LabelDTO> Labels { get; set; }

        /// <summary>
        /// The funnels in this flow snippet.
        /// </summary>
        /// <value>The funnels in this flow snippet.</value>
        [DataMember(Name="funnels", EmitDefaultValue=false)]
        public List<FunnelDTO> Funnels { get; set; }

        /// <summary>
        /// The controller services in this flow snippet.
        /// </summary>
        /// <value>The controller services in this flow snippet.</value>
        [DataMember(Name="controllerServices", EmitDefaultValue=false)]
        public List<ControllerServiceDTO> ControllerServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlowSnippetDTO {\n");
            sb.Append("  ProcessGroups: ").Append(this.ProcessGroups).Append("\n");
            sb.Append("  RemoteProcessGroups: ").Append(this.RemoteProcessGroups).Append("\n");
            sb.Append("  Processors: ").Append(this.Processors).Append("\n");
            sb.Append("  InputPorts: ").Append(this.InputPorts).Append("\n");
            sb.Append("  OutputPorts: ").Append(this.OutputPorts).Append("\n");
            sb.Append("  Connections: ").Append(this.Connections).Append("\n");
            sb.Append("  Labels: ").Append(this.Labels).Append("\n");
            sb.Append("  Funnels: ").Append(this.Funnels).Append("\n");
            sb.Append("  ControllerServices: ").Append(this.ControllerServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FlowSnippetDTO);
        }

        /// <summary>
        /// Returns true if FlowSnippetDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of FlowSnippetDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlowSnippetDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProcessGroups == input.ProcessGroups ||
                    this.ProcessGroups != null &&
                    this.ProcessGroups.SequenceEqual(input.ProcessGroups)
                ) && 
                (
                    this.RemoteProcessGroups == input.RemoteProcessGroups ||
                    this.RemoteProcessGroups != null &&
                    this.RemoteProcessGroups.SequenceEqual(input.RemoteProcessGroups)
                ) && 
                (
                    this.Processors == input.Processors ||
                    this.Processors != null &&
                    this.Processors.SequenceEqual(input.Processors)
                ) && 
                (
                    this.InputPorts == input.InputPorts ||
                    this.InputPorts != null &&
                    this.InputPorts.SequenceEqual(input.InputPorts)
                ) && 
                (
                    this.OutputPorts == input.OutputPorts ||
                    this.OutputPorts != null &&
                    this.OutputPorts.SequenceEqual(input.OutputPorts)
                ) && 
                (
                    this.Connections == input.Connections ||
                    this.Connections != null &&
                    this.Connections.SequenceEqual(input.Connections)
                ) && 
                (
                    this.Labels == input.Labels ||
                    this.Labels != null &&
                    this.Labels.SequenceEqual(input.Labels)
                ) && 
                (
                    this.Funnels == input.Funnels ||
                    this.Funnels != null &&
                    this.Funnels.SequenceEqual(input.Funnels)
                ) && 
                (
                    this.ControllerServices == input.ControllerServices ||
                    this.ControllerServices != null &&
                    this.ControllerServices.SequenceEqual(input.ControllerServices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProcessGroups != null)
                    hashCode = hashCode * 59 + this.ProcessGroups.GetHashCode();
                if (this.RemoteProcessGroups != null)
                    hashCode = hashCode * 59 + this.RemoteProcessGroups.GetHashCode();
                if (this.Processors != null)
                    hashCode = hashCode * 59 + this.Processors.GetHashCode();
                if (this.InputPorts != null)
                    hashCode = hashCode * 59 + this.InputPorts.GetHashCode();
                if (this.OutputPorts != null)
                    hashCode = hashCode * 59 + this.OutputPorts.GetHashCode();
                if (this.Connections != null)
                    hashCode = hashCode * 59 + this.Connections.GetHashCode();
                if (this.Labels != null)
                    hashCode = hashCode * 59 + this.Labels.GetHashCode();
                if (this.Funnels != null)
                    hashCode = hashCode * 59 + this.Funnels.GetHashCode();
                if (this.ControllerServices != null)
                    hashCode = hashCode * 59 + this.ControllerServices.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
