/* 
 * NiFi Rest Api
 *
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.9.1
 * Contact: dev@nifi.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace NiFi.Swagger.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;

    using Newtonsoft.Json;

    /// <summary>
    /// PropertyDescriptorEntity
    /// </summary>
    [DataContract]
    public partial class PropertyDescriptorEntity :  IEquatable<PropertyDescriptorEntity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyDescriptorEntity" /> class.
        /// </summary>
        /// <param name="propertyDescriptor">propertyDescriptor.</param>
        public PropertyDescriptorEntity(PropertyDescriptorDTO propertyDescriptor = default(PropertyDescriptorDTO))
        {
            this.PropertyDescriptor = propertyDescriptor;
        }
        
        /// <summary>
        /// Gets or Sets PropertyDescriptor
        /// </summary>
        [DataMember(Name="propertyDescriptor", EmitDefaultValue=false)]
        public PropertyDescriptorDTO PropertyDescriptor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PropertyDescriptorEntity {\n");
            sb.Append("  PropertyDescriptor: ").Append(this.PropertyDescriptor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PropertyDescriptorEntity);
        }

        /// <summary>
        /// Returns true if PropertyDescriptorEntity instances are equal
        /// </summary>
        /// <param name="input">Instance of PropertyDescriptorEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PropertyDescriptorEntity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PropertyDescriptor == input.PropertyDescriptor ||
                    (this.PropertyDescriptor != null &&
                    this.PropertyDescriptor.Equals(input.PropertyDescriptor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PropertyDescriptor != null)
                    hashCode = hashCode * 59 + this.PropertyDescriptor.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
