/* 
 * NiFi Rest Api
 *
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.9.1
 * Contact: dev@nifi.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace NiFi.Swagger.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;

    using Newtonsoft.Json;

    /// <summary>
    /// VersionedFlowSnapshotEntity
    /// </summary>
    [DataContract]
    public partial class VersionedFlowSnapshotEntity :  IEquatable<VersionedFlowSnapshotEntity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionedFlowSnapshotEntity" /> class.
        /// </summary>
        /// <param name="versionedFlowSnapshot">The versioned flow snapshot.</param>
        /// <param name="processGroupRevision">The Revision of the Process Group under Version Control.</param>
        /// <param name="registryId">The ID of the Registry that this flow belongs to.</param>
        /// <param name="updateDescendantVersionedFlows">If the Process Group to be updated has a child or descendant Process Group that is also under Version Control, this specifies whether or not the contents of that child/descendant Process Group should be updated..</param>
        /// <param name="disconnectedNodeAcknowledged">Acknowledges that this node is disconnected to allow for mutable requests to proceed..</param>
        public VersionedFlowSnapshotEntity(VersionedFlowSnapshot versionedFlowSnapshot = default(VersionedFlowSnapshot), RevisionDTO processGroupRevision = default(RevisionDTO), string registryId = default(string), bool? updateDescendantVersionedFlows = default(bool?), bool? disconnectedNodeAcknowledged = default(bool?))
        {
            this.VersionedFlowSnapshot = versionedFlowSnapshot;
            this.ProcessGroupRevision = processGroupRevision;
            this.RegistryId = registryId;
            this.UpdateDescendantVersionedFlows = updateDescendantVersionedFlows;
            this.DisconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
        }
        
        /// <summary>
        /// The versioned flow snapshot
        /// </summary>
        /// <value>The versioned flow snapshot</value>
        [DataMember(Name="versionedFlowSnapshot", EmitDefaultValue=false)]
        public VersionedFlowSnapshot VersionedFlowSnapshot { get; set; }

        /// <summary>
        /// The Revision of the Process Group under Version Control
        /// </summary>
        /// <value>The Revision of the Process Group under Version Control</value>
        [DataMember(Name="processGroupRevision", EmitDefaultValue=false)]
        public RevisionDTO ProcessGroupRevision { get; set; }

        /// <summary>
        /// The ID of the Registry that this flow belongs to
        /// </summary>
        /// <value>The ID of the Registry that this flow belongs to</value>
        [DataMember(Name="registryId", EmitDefaultValue=false)]
        public string RegistryId { get; set; }

        /// <summary>
        /// If the Process Group to be updated has a child or descendant Process Group that is also under Version Control, this specifies whether or not the contents of that child/descendant Process Group should be updated.
        /// </summary>
        /// <value>If the Process Group to be updated has a child or descendant Process Group that is also under Version Control, this specifies whether or not the contents of that child/descendant Process Group should be updated.</value>
        [DataMember(Name="updateDescendantVersionedFlows", EmitDefaultValue=false)]
        public bool? UpdateDescendantVersionedFlows { get; set; }

        /// <summary>
        /// Acknowledges that this node is disconnected to allow for mutable requests to proceed.
        /// </summary>
        /// <value>Acknowledges that this node is disconnected to allow for mutable requests to proceed.</value>
        [DataMember(Name="disconnectedNodeAcknowledged", EmitDefaultValue=false)]
        public bool? DisconnectedNodeAcknowledged { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VersionedFlowSnapshotEntity {\n");
            sb.Append("  VersionedFlowSnapshot: ").Append(this.VersionedFlowSnapshot).Append("\n");
            sb.Append("  ProcessGroupRevision: ").Append(this.ProcessGroupRevision).Append("\n");
            sb.Append("  RegistryId: ").Append(this.RegistryId).Append("\n");
            sb.Append("  UpdateDescendantVersionedFlows: ").Append(this.UpdateDescendantVersionedFlows).Append("\n");
            sb.Append("  DisconnectedNodeAcknowledged: ").Append(this.DisconnectedNodeAcknowledged).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VersionedFlowSnapshotEntity);
        }

        /// <summary>
        /// Returns true if VersionedFlowSnapshotEntity instances are equal
        /// </summary>
        /// <param name="input">Instance of VersionedFlowSnapshotEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VersionedFlowSnapshotEntity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VersionedFlowSnapshot == input.VersionedFlowSnapshot ||
                    (this.VersionedFlowSnapshot != null &&
                    this.VersionedFlowSnapshot.Equals(input.VersionedFlowSnapshot))
                ) && 
                (
                    this.ProcessGroupRevision == input.ProcessGroupRevision ||
                    (this.ProcessGroupRevision != null &&
                    this.ProcessGroupRevision.Equals(input.ProcessGroupRevision))
                ) && 
                (
                    this.RegistryId == input.RegistryId ||
                    (this.RegistryId != null &&
                    this.RegistryId.Equals(input.RegistryId))
                ) && 
                (
                    this.UpdateDescendantVersionedFlows == input.UpdateDescendantVersionedFlows ||
                    (this.UpdateDescendantVersionedFlows != null &&
                    this.UpdateDescendantVersionedFlows.Equals(input.UpdateDescendantVersionedFlows))
                ) && 
                (
                    this.DisconnectedNodeAcknowledged == input.DisconnectedNodeAcknowledged ||
                    (this.DisconnectedNodeAcknowledged != null &&
                    this.DisconnectedNodeAcknowledged.Equals(input.DisconnectedNodeAcknowledged))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VersionedFlowSnapshot != null)
                    hashCode = hashCode * 59 + this.VersionedFlowSnapshot.GetHashCode();
                if (this.ProcessGroupRevision != null)
                    hashCode = hashCode * 59 + this.ProcessGroupRevision.GetHashCode();
                if (this.RegistryId != null)
                    hashCode = hashCode * 59 + this.RegistryId.GetHashCode();
                if (this.UpdateDescendantVersionedFlows != null)
                    hashCode = hashCode * 59 + this.UpdateDescendantVersionedFlows.GetHashCode();
                if (this.DisconnectedNodeAcknowledged != null)
                    hashCode = hashCode * 59 + this.DisconnectedNodeAcknowledged.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
